version: '3.3'

services:
  # Expose dev secrets as a plain volume - these will use docker secrets in staging and prod
  auth:
    volumes:
      - '.secrets/public-key.pem:/secrets/public-key.pem'
      - '.secrets/private-key.pem:/secrets/private-key.pem'
    environment:
      - CERT_PUBLIC_KEY_PATH=/secrets/public-key.pem
      - CERT_PRIVATE_KEY_PATH=/secrets/private-key.pem
    ports:
      - '4040:4040'

  user-mgnt:
    volumes:
      - '.secrets/public-key.pem:/secrets/public-key.pem'
    environment:
      - CERT_PUBLIC_KEY_PATH=/secrets/public-key.pem
      - HOST=0.0.0.0
    ports:
      - '3030:3030'

  notification:
    volumes:
      - '.secrets/public-key.pem:/secrets/public-key.pem'
    environment:
      - CERT_PUBLIC_KEY_PATH=/secrets/public-key.pem
    ports:
      - '2020:2020'

  gateway:
    volumes:
      - '.secrets/public-key.pem:/secrets/public-key.pem'
    environment:
      - CERT_PUBLIC_KEY_PATH=/secrets/public-key.pem
    ports:
      - '7070:7070'

  workflow:
    volumes:
      - '.secrets/public-key.pem:/secrets/public-key.pem'
    environment:
      - CERT_PUBLIC_KEY_PATH=/secrets/public-key.pem
    ports:
      - '5050:5050'

  search:
    volumes:
      - '.secrets/public-key.pem:/secrets/public-key.pem'
    environment:
      - CERT_PUBLIC_KEY_PATH=/secrets/public-key.pem
    ports:
      - '9090:9090'

  resources:
    volumes:
      - '.secrets/public-key.pem:/secrets/public-key.pem'
    environment:
      - CERT_PUBLIC_KEY_PATH=/secrets/public-key.pem
    ports:
      - '3040:3040'

  metrics:
    volumes:
      - '.secrets/public-key.pem:/secrets/public-key.pem'
    environment:
      - CERT_PUBLIC_KEY_PATH=/secrets/public-key.pem
    ports:
      - '1050:1050'

  register:
    ports:
      - '3000:80'
  performance:
    ports:
      - '3001:80'
  login:
    ports:
      - '3020:80'
  styleguide:
    ports:
      - '6060:6060'
