# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# OpenCRVS is also distributed under the terms of the Civil Registration
# & Healthcare Disclaimer located at http://opencrvs.org/license.
#
# Copyright (C) The OpenCRVS Authors. OpenCRVS and the OpenCRVS
# graphic logo are (registered/a) trademark(s) of Plan International.
version: '3.3'

services:
  client:
    image: jembi/ocrvs-client:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./packages/client/Dockerfile
    restart: unless-stopped

  login:
    image: jembi/ocrvs-login:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./packages/login/Dockerfile
    restart: unless-stopped

  styleguide:
    image: jembi/ocrvs-styleguide:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./packages/components/Dockerfile
    restart: unless-stopped

  gateway:
    image: jembi/ocrvs-gateway:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./packages/gateway/Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - FHIR_URL=http://openhim-core:5001/fhir
      - USER_MANAGEMENT_URL=http://user-mgnt:3030/
      - SEARCH_URL=http://search:9090/
      - METRICS_URL=http://metrics:1050
      - AUTH_URL=http://auth:4040
      - RESOURCES_URL=http://resources:3040
      - NOTIFICATION_URL=http://notification:2020/
      - WORKFLOW_URL=http://workflow:5050/

  # User facing services
  workflow:
    image: jembi/ocrvs-workflow:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./packages/workflow/Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - NOTIFICATION_SERVICE_URL=http://notification:2020/
      - USER_MANAGEMENT_URL=http://user-mgnt:3030/
      - RESOURCE_SERVICE_URL=http://resources:3040/${COUNTRY:-bgd}/
      - HEARTH_URL=http://hearth:3447/fhir
      - OPENHIM_URL=http://openhim-core:5001
      - COUNTRY=${COUNTRY:-bgd} # PEN_TEST change to gbr
      - AUTH_URL=http://auth:4040
      - CHECK_INVALID_TOKEN=true

  search:
    image: jembi/ocrvs-search:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./packages/search/Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - USER_MANAGEMENT_URL=http://user-mgnt:3030/
      - ES_HOST=elasticsearch:9200
      - HEARTH_URL=http://hearth:3447/fhir
      - AUTH_URL=http://auth:4040
      - CHECK_INVALID_TOKEN=true

  metrics:
    image: jembi/ocrvs-metrics:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./packages/metrics/Dockerfile
    restart: unless-stopped
    environment:
      - INFLUX_HOST=influxdb
      - INFLUX_PORT=8086
      - INFLUX_DB=ocrvs
      - AUTH_URL=http://auth:4040
      - CHECK_INVALID_TOKEN=true
      - FHIR_URL=http://openhim-core:5001/fhir

  # END User facing services

  auth:
    image: jembi/ocrvs-auth:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./packages/auth/Dockerfile
    restart: unless-stopped
    environment:
      - REDIS_HOST=redis
      - USER_MANAGEMENT_URL=http://user-mgnt:3030/
      - CONFIG_TOKEN_EXPIRY_SECONDS=604800
      - CONFIG_SMS_CODE_EXPIRY_SECONDS=600
      - NOTIFICATION_SERVICE_URL=http://notification:2020/

  user-mgnt:
    image: jembi/ocrvs-user-mgnt:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./packages/user-mgnt/Dockerfile
    restart: unless-stopped
    environment:
      - MONGO_URL=mongodb://mongo1/user-mgnt
      - AUTH_URL=http://auth:4040
      - NOTIFICATION_SERVICE_URL=http://notification:2020/
      - FHIR_URL=http://openhim-core:5001/fhir
      - HOST=0.0.0.0

  notification:
    image: jembi/ocrvs-notification:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./packages/notification/Dockerfile
    restart: unless-stopped
    environment:
      - AUTH_URL=http://auth:4040
      - COUNTRY=${COUNTRY:-bgd}
      - HOST=0.0.0.0

  resources:
    image: jembi/ocrvs-resources:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./packages/resources/Dockerfile
    restart: unless-stopped
    environment:
      - MONGO_URL=mongodb://mongo1/user-mgnt
      - TEST_USER_PASSWORD=test
      - NODE_ENV=development
      - FHIR_URL=http://hearth:3447/fhir
      - AUTH_URL=http://auth:4040
      - OPENHIM_URL=http://openhim-core:5001
      - CONFIRM_REGISTRATION_URL=http://workflow:5050/confirm/registration
