logLevel = "INFO"
defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[api]

[ping]

[docker]
domain = "{{hostname}}"
swarmMode = true
exposedByDefault = false
watch = true

[acme]
email = "ryan@jembi.org"
storage = "acme.json"
entryPoint = "https"
onHostRule = true

[acme.httpChallenge]
entryPoint = "http"

[[acme.domains]]
  main = "{{hostname}}"
  sans = ["register.{{hostname}}", "login.{{hostname}}", "auth.{{hostname}}", "gateway.{{hostname}}", "performance.{{hostname}}", "resources.{{hostname}}"]

[retry]
